from setuptools import setup, find_packages

setup(
    name="etl_flow",
    version="0.1.0",
    description="ETL workflow system with Azure Blob Storage integration and Windows Task Scheduler automation.",
    author="Andreas Rasmusson",
    packages=find_packages(),
    install_requires=[
        "asttokens==3.0.0",
        "attrs==25.3.0",
        "azure-core==1.35.0",
        "azure-storage-blob==12.26.0",
        "certifi==2025.8.3",
        "cffi==1.17.1",
        "charset-normalizer==3.4.3",
        "colorama==0.4.6",
        "comm==0.2.3",
        "cryptography==45.0.6",
        "debugpy==1.8.16",
        "decorator==5.2.1",
        "exceptiongroup==1.3.0",
        "executing==2.2.0",
        "idna==3.10",
        "iniconfig==2.1.0",
        "ipykernel==6.30.1",
        "ipython==8.37.0",
        "isodate==0.7.2",
        "jedi==0.19.2",
        "jsonschema==4.25.1",
        "jsonschema-specifications==2025.4.1",
        "jupyter_client==8.6.3",
        "jupyter_core==5.8.1",
        "matplotlib-inline==0.1.7",
        "nest-asyncio==1.6.0",
        "packaging==25.0",
        "parso==0.8.5",
        "platformdirs==4.4.0",
        "pluggy==1.6.0",
        "prompt_toolkit==3.0.52",
        "psutil==7.0.0",
        "pure_eval==0.2.3",
        "pyaml==25.7.0",
        "pycparser==2.22",
        "Pygments==2.19.2",
        "pytest==8.4.1",
        "python-dateutil==2.9.0.post0",
        "pywin32==311",
        "PyYAML==6.0.2",
        "pyzmq==27.0.2",
        "referencing==0.36.2",
        "requests==2.32.5",
        "rpds-py==0.27.1",
        "six==1.17.0",
        "stack-data==0.6.3",
        "tomli==2.2.1",
        "tornado==6.5.2",
        "traitlets==5.14.3",
        "typing_extensions==4.15.0",
        "urllib3==2.5.0",
        "wcwidth==0.2.13"
    ],
    entry_points={
        "console_scripts": [
            "etl-flow = etl_flow.etl_job:main",
            "etl-flow-schedule = etl_flow.scheduling.scheduling:main"
        ]
    },
    include_package_data=True,
    python_requires=">=3.10",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: Microsoft :: Windows"
    ],
)